### ISSUE TITLE
Missing events on crucial functions and important state changes

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/TokenNFTConnector#46]
**Issue ID**
LDN-13

**Risk Level**
Severity: Informational

**Risk Level**
Severity: Informational

**Code Location**
```
TokenNFTConnector/contracts/ConnectorManageable.sol
TokenNFTConnector/contracts/TokenNFTConnector.sol
```

**Description**
   It has been observed that important functionality is missing emitting events for some functions: **ConnectorManageable.setProjectOwnerFee, ConnectorManageable.withdrawFee, TokenNFTConnector.createLeaderboard, SimpleBuilder.buildMassPools** and **SimpleRefundBuilder.buildMassPools**. These functions should emit events. Events are a method of informing the transaction initiator about the actions taken by the called function.
   
**Recommendation**
Make sure to emit events in all essential functions.

**Comment by YouStillAlive** [comment]
Do we want these changes?

**Comment by Lomet** [comment]
> Do we need these changes?

yes. events are good
